---
  - name: "update and update apt packages."
    become: true
    apt:
      update_cache: yes
      upgrade: yes
  
  - name: "Install Nodejs and npm"
    apt:
      name:
        - nodejs
        - npm
      state: present
      update_cache: yes

  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

      
